FROM maven AS BUILD_IMAGE
COPY ./payment-service payment-MS
RUN cd payment-MS && mvn install -B

FROM openjdk:8-jdk-alpine
LABEL "Project"="Payment-Service"
LABEL "Author"="Sergio"
WORKDIR /app
COPY --from=BUILD_IMAGE payment-MS/target/payments-service-example-0.0.1-SNAPSHOT.jar /app/products-service.jar
EXPOSE 8080
CMD ["java","-jar", "/app/products-service.jar"]
