name: PaymentService analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: payment-service

    steps:
      - name: Code checkout 
        uses: actions/checkout@v4

      - name: test maven
        run: mvn clean test install
      
                    
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '11'   
       
 
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=CAScompany_project-PaymentService
            -Dsonar.organization=cascompany
            -Dsonar.java.binaries=**/target/classes
            -Dsonar.sources=.
            -Dsonar.junit.reportsPath=target/surefire-reports/
            -Dsonar.junit.reportsPath=target/checckstyle-result.xml
            -Dsonar.jacoco.reportsPathtarjet/jacoco.exec
            -Dsonar.java.checkstyle.reportPath=target/checkstyle-result.xml



